import raw from "../data/stdlib-c4.generated.json";

/**
 * Macro signatures of PlantUML's bundled C4 standard library, generated by
 * scripts/generate-plantuml-stdlib.mjs. Offered only when the document
 * includes the corresponding file (`!include <C4/C4_Container>`).
 */
export interface StdlibMacro {
  library: string;
  name: string;
  params: { name: string; optional: boolean }[];
}

interface StdlibFile {
  includes: string[];
  macros: { name: string; params: { name: string; optional: boolean }[] }[];
}

const data: { library: string; version: string; files: Record<string, StdlibFile> } = raw;
const fileNames = Object.keys(data.files);
const byLowerName = new Map(fileNames.map((name) => [name.toLowerCase(), name]));

/** Paths completable after `!include <`. */
export function stdlibIncludePaths(): string[] {
  return fileNames.filter((name) => name !== data.library).map((name) => `${data.library}/${name}`);
}

/** The library file an `!include` target refers to: `<C4/C4_Context>` or a C4-PlantUML URL. */
function includedFile(target: string): string | undefined {
  const m = /<C4\/(\w+)(?:\.puml)?>/i.exec(target) ?? /C4-PlantUML\/.*\/(C4\w*)\.puml/i.exec(target);
  return m ? byLowerName.get(m[1].toLowerCase()) : undefined;
}

const cache = new Map<string, StdlibMacro[]>();

/** Macros made available by a document's `!include` lines (with the files those include). */
export function stdlibMacrosFor(includes: string[]): StdlibMacro[] {
  if (includes.length === 0) return [];
  const key = includes.join("\n");
  const hit = cache.get(key);
  if (hit) return hit;
  const seen = new Set<string>();
  const macros = new Map<string, StdlibMacro>();
  const visit = (file: string) => {
    if (seen.has(file)) return;
    seen.add(file);
    const entry = data.files[file];
    if (!entry) return;
    // The including file's definitions win over the ones it builds on.
    for (const macro of entry.macros) {
      if (!macros.has(macro.name)) macros.set(macro.name, { library: `${data.library}/${file}`, ...macro });
    }
    entry.includes.forEach(visit);
  };
  for (const target of includes) {
    const file = includedFile(target);
    if (file) visit(file);
  }
  const result = [...macros.values()];
  cache.set(key, result);
  return result;
}

export function stdlibMacro(name: string, includes: string[]): StdlibMacro | undefined {
  return stdlibMacrosFor(includes).find((macro) => macro.name === name);
}
